services:
  - type: web
    name: timetable-generator
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn timetable_generator.wsgi"
    envVars:
      - key: DEBUG
        value: "False"
