# Generated by Django 4.2.16 on 2025-04-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='department',
            field=models.CharField(default='computer system and mathematics', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='program_degree',
            field=models.CharField(default='ism', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='school',
            field=models.CharField(default='bussiness', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(default='2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='yearofstudy',
            name='total_students',
            field=models.PositiveIntegerField(),
        ),
    ]
